
# PowerShell 5.0 Image
os: WMF 5

# Clone Directory
clone_folder: C:\Projects\ISEPresenter

# Build Number
version: '1.0.0.{build}'

# Build Prepare
before_build:
- ps: nuget restore

# Execute Build
configuration: Release
platform: Any CPU
build:
  project: ISEPresenter.sln
  verbosity: minimal

# Publish Release
artifacts:
- path: bin\Release
  name: ISEPresenter
