//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEPresenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISEPresenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Up key.
        /// </summary>
        internal static string RemoteControlDevice_GenericKeyboard_BackDescription {
            get {
                return ResourceManager.GetString("RemoteControlDevice_GenericKeyboard_BackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete key.
        /// </summary>
        internal static string RemoteControlDevice_GenericKeyboard_ClearDescription {
            get {
                return ResourceManager.GetString("RemoteControlDevice_GenericKeyboard_ClearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Keyboard.
        /// </summary>
        internal static string RemoteControlDevice_GenericKeyboard_DeviceName {
            get {
                return ResourceManager.GetString("RemoteControlDevice_GenericKeyboard_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Down key.
        /// </summary>
        internal static string RemoteControlDevice_GenericKeyboard_ForwardDescription {
            get {
                return ResourceManager.GetString("RemoteControlDevice_GenericKeyboard_ForwardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5 or F8 function key.
        /// </summary>
        internal static string RemoteControlDevice_GenericKeyboard_RunDescription {
            get {
                return ResourceManager.GetString("RemoteControlDevice_GenericKeyboard_RunDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide back button.
        /// </summary>
        internal static string RemoteControlDevice_LogitechRemoteR400_BackDescription {
            get {
                return ResourceManager.GetString("RemoteControlDevice_LogitechRemoteR400_BackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank screen button.
        /// </summary>
        internal static string RemoteControlDevice_LogitechRemoteR400_ClearDescription {
            get {
                return ResourceManager.GetString("RemoteControlDevice_LogitechRemoteR400_ClearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logitech Remote R400.
        /// </summary>
        internal static string RemoteControlDevice_LogitechRemoteR400_DeviceName {
            get {
                return ResourceManager.GetString("RemoteControlDevice_LogitechRemoteR400_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide forward button.
        /// </summary>
        internal static string RemoteControlDevice_LogitechRemoteR400_ForwardDescription {
            get {
                return ResourceManager.GetString("RemoteControlDevice_LogitechRemoteR400_ForwardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch slide show button.
        /// </summary>
        internal static string RemoteControlDevice_LogitechRemoteR400_RunDescription {
            get {
                return ResourceManager.GetString("RemoteControlDevice_LogitechRemoteR400_RunDescription", resourceCulture);
            }
        }
    }
}
